//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThueXe.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HOPDONGTHUE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class HOPDONGTHUE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SoDDTField;
        
        private int MaXeField;
        
        private int GiaThueField;
        
        private int MucGiamGiaField;
        
        private System.DateTime NgayThueField;
        
        private System.DateTime NgayTraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrangThaiField;
        
        private int MaKHField;
        
        private int MaNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLiThueXe.ServiceReference1.CHITIETXE CHITIETXEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLiThueXe.ServiceReference1.KHACHHANG KHACHHANGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLiThueXe.ServiceReference1.NHANVIEN NHANVIENField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SoDDT {
            get {
                return this.SoDDTField;
            }
            set {
                if ((this.SoDDTField.Equals(value) != true)) {
                    this.SoDDTField = value;
                    this.RaisePropertyChanged("SoDDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int MaXe {
            get {
                return this.MaXeField;
            }
            set {
                if ((this.MaXeField.Equals(value) != true)) {
                    this.MaXeField = value;
                    this.RaisePropertyChanged("MaXe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int GiaThue {
            get {
                return this.GiaThueField;
            }
            set {
                if ((this.GiaThueField.Equals(value) != true)) {
                    this.GiaThueField = value;
                    this.RaisePropertyChanged("GiaThue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int MucGiamGia {
            get {
                return this.MucGiamGiaField;
            }
            set {
                if ((this.MucGiamGiaField.Equals(value) != true)) {
                    this.MucGiamGiaField = value;
                    this.RaisePropertyChanged("MucGiamGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime NgayThue {
            get {
                return this.NgayThueField;
            }
            set {
                if ((this.NgayThueField.Equals(value) != true)) {
                    this.NgayThueField = value;
                    this.RaisePropertyChanged("NgayThue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime NgayTra {
            get {
                return this.NgayTraField;
            }
            set {
                if ((this.NgayTraField.Equals(value) != true)) {
                    this.NgayTraField = value;
                    this.RaisePropertyChanged("NgayTra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TrangThaiField, value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int MaNV {
            get {
                return this.MaNVField;
            }
            set {
                if ((this.MaNVField.Equals(value) != true)) {
                    this.MaNVField = value;
                    this.RaisePropertyChanged("MaNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public QuanLiThueXe.ServiceReference1.CHITIETXE CHITIETXE {
            get {
                return this.CHITIETXEField;
            }
            set {
                if ((object.ReferenceEquals(this.CHITIETXEField, value) != true)) {
                    this.CHITIETXEField = value;
                    this.RaisePropertyChanged("CHITIETXE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public QuanLiThueXe.ServiceReference1.KHACHHANG KHACHHANG {
            get {
                return this.KHACHHANGField;
            }
            set {
                if ((object.ReferenceEquals(this.KHACHHANGField, value) != true)) {
                    this.KHACHHANGField = value;
                    this.RaisePropertyChanged("KHACHHANG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public QuanLiThueXe.ServiceReference1.NHANVIEN NHANVIEN {
            get {
                return this.NHANVIENField;
            }
            set {
                if ((object.ReferenceEquals(this.NHANVIENField, value) != true)) {
                    this.NHANVIENField = value;
                    this.RaisePropertyChanged("NHANVIEN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CHITIETXE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CHITIETXE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaXEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenXEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BangSoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrangThaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MauSacField;
        
        private int DonGiaField;
        
        private int MaNCCField;
        
        private int MaLXField;
        
        private System.Nullable<int> MaKHField;
        
        private System.Nullable<int> MucGiamGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLiThueXe.ServiceReference1.KHACHHANG KHACHHANGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLiThueXe.ServiceReference1.LOAIXE LOAIXEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QuanLiThueXe.ServiceReference1.NHACUNGCAP NHACUNGCAPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaXE {
            get {
                return this.MaXEField;
            }
            set {
                if ((this.MaXEField.Equals(value) != true)) {
                    this.MaXEField = value;
                    this.RaisePropertyChanged("MaXE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenXE {
            get {
                return this.TenXEField;
            }
            set {
                if ((object.ReferenceEquals(this.TenXEField, value) != true)) {
                    this.TenXEField = value;
                    this.RaisePropertyChanged("TenXE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BangSo {
            get {
                return this.BangSoField;
            }
            set {
                if ((object.ReferenceEquals(this.BangSoField, value) != true)) {
                    this.BangSoField = value;
                    this.RaisePropertyChanged("BangSo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TrangThaiField, value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MauSac {
            get {
                return this.MauSacField;
            }
            set {
                if ((object.ReferenceEquals(this.MauSacField, value) != true)) {
                    this.MauSacField = value;
                    this.RaisePropertyChanged("MauSac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int MaNCC {
            get {
                return this.MaNCCField;
            }
            set {
                if ((this.MaNCCField.Equals(value) != true)) {
                    this.MaNCCField = value;
                    this.RaisePropertyChanged("MaNCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int MaLX {
            get {
                return this.MaLXField;
            }
            set {
                if ((this.MaLXField.Equals(value) != true)) {
                    this.MaLXField = value;
                    this.RaisePropertyChanged("MaLX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> MucGiamGia {
            get {
                return this.MucGiamGiaField;
            }
            set {
                if ((this.MucGiamGiaField.Equals(value) != true)) {
                    this.MucGiamGiaField = value;
                    this.RaisePropertyChanged("MucGiamGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public QuanLiThueXe.ServiceReference1.KHACHHANG KHACHHANG {
            get {
                return this.KHACHHANGField;
            }
            set {
                if ((object.ReferenceEquals(this.KHACHHANGField, value) != true)) {
                    this.KHACHHANGField = value;
                    this.RaisePropertyChanged("KHACHHANG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public QuanLiThueXe.ServiceReference1.LOAIXE LOAIXE {
            get {
                return this.LOAIXEField;
            }
            set {
                if ((object.ReferenceEquals(this.LOAIXEField, value) != true)) {
                    this.LOAIXEField = value;
                    this.RaisePropertyChanged("LOAIXE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public QuanLiThueXe.ServiceReference1.NHACUNGCAP NHACUNGCAP {
            get {
                return this.NHACUNGCAPField;
            }
            set {
                if ((object.ReferenceEquals(this.NHACUNGCAPField, value) != true)) {
                    this.NHACUNGCAPField = value;
                    this.RaisePropertyChanged("NHACUNGCAP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KHACHHANG", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KHACHHANG : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamSinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CMNDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NamSinh {
            get {
                return this.NamSinhField;
            }
            set {
                if ((object.ReferenceEquals(this.NamSinhField, value) != true)) {
                    this.NamSinhField = value;
                    this.RaisePropertyChanged("NamSinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CMND {
            get {
                return this.CMNDField;
            }
            set {
                if ((object.ReferenceEquals(this.CMNDField, value) != true)) {
                    this.CMNDField = value;
                    this.RaisePropertyChanged("CMND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NHANVIEN", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NHANVIEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaNV {
            get {
                return this.MaNVField;
            }
            set {
                if ((this.MaNVField.Equals(value) != true)) {
                    this.MaNVField = value;
                    this.RaisePropertyChanged("MaNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LOAIXE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LOAIXE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((this.MaLoaiField.Equals(value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenLoai {
            get {
                return this.TenLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiField, value) != true)) {
                    this.TenLoaiField = value;
                    this.RaisePropertyChanged("TenLoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NHACUNGCAP", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NHACUNGCAP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaNCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNCCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaNCC {
            get {
                return this.MaNCCField;
            }
            set {
                if ((this.MaNCCField.Equals(value) != true)) {
                    this.MaNCCField = value;
                    this.RaisePropertyChanged("MaNCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenNCC {
            get {
                return this.TenNCCField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNCCField, value) != true)) {
                    this.TenNCCField = value;
                    this.RaisePropertyChanged("TenNCC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CHITIETXE1", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CHITIETXE1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaXeField;
        
        private int GiaThueField;
        
        private System.Nullable<int> MucGiamGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoaiXeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HangXeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BangSoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MauSacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrangThaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaXe {
            get {
                return this.MaXeField;
            }
            set {
                if ((this.MaXeField.Equals(value) != true)) {
                    this.MaXeField = value;
                    this.RaisePropertyChanged("MaXe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int GiaThue {
            get {
                return this.GiaThueField;
            }
            set {
                if ((this.GiaThueField.Equals(value) != true)) {
                    this.GiaThueField = value;
                    this.RaisePropertyChanged("GiaThue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> MucGiamGia {
            get {
                return this.MucGiamGiaField;
            }
            set {
                if ((this.MucGiamGiaField.Equals(value) != true)) {
                    this.MucGiamGiaField = value;
                    this.RaisePropertyChanged("MucGiamGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LoaiXe {
            get {
                return this.LoaiXeField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiXeField, value) != true)) {
                    this.LoaiXeField = value;
                    this.RaisePropertyChanged("LoaiXe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HangXe {
            get {
                return this.HangXeField;
            }
            set {
                if ((object.ReferenceEquals(this.HangXeField, value) != true)) {
                    this.HangXeField = value;
                    this.RaisePropertyChanged("HangXe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BangSo {
            get {
                return this.BangSoField;
            }
            set {
                if ((object.ReferenceEquals(this.BangSoField, value) != true)) {
                    this.BangSoField = value;
                    this.RaisePropertyChanged("BangSo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MauSac {
            get {
                return this.MauSacField;
            }
            set {
                if ((object.ReferenceEquals(this.MauSacField, value) != true)) {
                    this.MauSacField = value;
                    this.RaisePropertyChanged("MauSac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TrangThaiField, value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="THANHTOAN", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class THANHTOAN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SoDDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenNVField;
        
        private System.Nullable<int> GiaThueNgayField;
        
        private System.Nullable<System.DateTime> NgayTraField;
        
        private int SoNgayField;
        
        private System.Nullable<System.DateTime> NgayThueField;
        
        private System.Nullable<double> ThanhTienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SoDDT {
            get {
                return this.SoDDTField;
            }
            set {
                if ((this.SoDDTField.Equals(value) != true)) {
                    this.SoDDTField = value;
                    this.RaisePropertyChanged("SoDDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HoTenKH {
            get {
                return this.HoTenKHField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenKHField, value) != true)) {
                    this.HoTenKHField = value;
                    this.RaisePropertyChanged("HoTenKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HoTenNV {
            get {
                return this.HoTenNVField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenNVField, value) != true)) {
                    this.HoTenNVField = value;
                    this.RaisePropertyChanged("HoTenNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> GiaThueNgay {
            get {
                return this.GiaThueNgayField;
            }
            set {
                if ((this.GiaThueNgayField.Equals(value) != true)) {
                    this.GiaThueNgayField = value;
                    this.RaisePropertyChanged("GiaThueNgay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> NgayTra {
            get {
                return this.NgayTraField;
            }
            set {
                if ((this.NgayTraField.Equals(value) != true)) {
                    this.NgayTraField = value;
                    this.RaisePropertyChanged("NgayTra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int SoNgay {
            get {
                return this.SoNgayField;
            }
            set {
                if ((this.SoNgayField.Equals(value) != true)) {
                    this.SoNgayField = value;
                    this.RaisePropertyChanged("SoNgay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> NgayThue {
            get {
                return this.NgayThueField;
            }
            set {
                if ((this.NgayThueField.Equals(value) != true)) {
                    this.NgayThueField = value;
                    this.RaisePropertyChanged("NgayThue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<double> ThanhTien {
            get {
                return this.ThanhTienField;
            }
            set {
                if ((this.ThanhTienField.Equals(value) != true)) {
                    this.ThanhTienField = value;
                    this.RaisePropertyChanged("ThanhTien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.QLTXMSoap")]
    public interface QLTXMSoap {
        
        // CODEGEN: Generating message contract since element name DanhSachThueResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThue", ReplyAction="*")]
        QuanLiThueXe.ServiceReference1.DanhSachThueResponse DanhSachThue(QuanLiThueXe.ServiceReference1.DanhSachThueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThue", ReplyAction="*")]
        System.Threading.Tasks.Task<QuanLiThueXe.ServiceReference1.DanhSachThueResponse> DanhSachThueAsync(QuanLiThueXe.ServiceReference1.DanhSachThueRequest request);
        
        // CODEGEN: Generating message contract since element name DanhSachThueChuaThanhToanResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThueChuaThanhToan", ReplyAction="*")]
        QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanResponse DanhSachThueChuaThanhToan(QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachThueChuaThanhToan", ReplyAction="*")]
        System.Threading.Tasks.Task<QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanResponse> DanhSachThueChuaThanhToanAsync(QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanRequest request);
        
        // CODEGEN: Generating message contract since element name DanhSachXeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachXe", ReplyAction="*")]
        QuanLiThueXe.ServiceReference1.DanhSachXeResponse DanhSachXe(QuanLiThueXe.ServiceReference1.DanhSachXeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhSachXe", ReplyAction="*")]
        System.Threading.Tasks.Task<QuanLiThueXe.ServiceReference1.DanhSachXeResponse> DanhSachXeAsync(QuanLiThueXe.ServiceReference1.DanhSachXeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemHopDongThue", ReplyAction="*")]
        void ThemHopDongThue(int maxe, int makh, int manv, System.DateTime ngaythue, System.DateTime ngaytra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemHopDongThue", ReplyAction="*")]
        System.Threading.Tasks.Task ThemHopDongThueAsync(int maxe, int makh, int manv, System.DateTime ngaythue, System.DateTime ngaytra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CapNhatHopDong", ReplyAction="*")]
        void CapNhatHopDong(int sddt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CapNhatHopDong", ReplyAction="*")]
        System.Threading.Tasks.Task CapNhatHopDongAsync(int sddt);
        
        // CODEGEN: Generating message contract since element name ThanhToanTienResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThanhToanTien", ReplyAction="*")]
        QuanLiThueXe.ServiceReference1.ThanhToanTienResponse ThanhToanTien(QuanLiThueXe.ServiceReference1.ThanhToanTienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThanhToanTien", ReplyAction="*")]
        System.Threading.Tasks.Task<QuanLiThueXe.ServiceReference1.ThanhToanTienResponse> ThanhToanTienAsync(QuanLiThueXe.ServiceReference1.ThanhToanTienRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DanhSachThueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DanhSachThue", Namespace="http://tempuri.org/", Order=0)]
        public QuanLiThueXe.ServiceReference1.DanhSachThueRequestBody Body;
        
        public DanhSachThueRequest() {
        }
        
        public DanhSachThueRequest(QuanLiThueXe.ServiceReference1.DanhSachThueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DanhSachThueRequestBody {
        
        public DanhSachThueRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DanhSachThueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DanhSachThueResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuanLiThueXe.ServiceReference1.DanhSachThueResponseBody Body;
        
        public DanhSachThueResponse() {
        }
        
        public DanhSachThueResponse(QuanLiThueXe.ServiceReference1.DanhSachThueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DanhSachThueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuanLiThueXe.ServiceReference1.HOPDONGTHUE[] DanhSachThueResult;
        
        public DanhSachThueResponseBody() {
        }
        
        public DanhSachThueResponseBody(QuanLiThueXe.ServiceReference1.HOPDONGTHUE[] DanhSachThueResult) {
            this.DanhSachThueResult = DanhSachThueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DanhSachThueChuaThanhToanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DanhSachThueChuaThanhToan", Namespace="http://tempuri.org/", Order=0)]
        public QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanRequestBody Body;
        
        public DanhSachThueChuaThanhToanRequest() {
        }
        
        public DanhSachThueChuaThanhToanRequest(QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DanhSachThueChuaThanhToanRequestBody {
        
        public DanhSachThueChuaThanhToanRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DanhSachThueChuaThanhToanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DanhSachThueChuaThanhToanResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanResponseBody Body;
        
        public DanhSachThueChuaThanhToanResponse() {
        }
        
        public DanhSachThueChuaThanhToanResponse(QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DanhSachThueChuaThanhToanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuanLiThueXe.ServiceReference1.HOPDONGTHUE[] DanhSachThueChuaThanhToanResult;
        
        public DanhSachThueChuaThanhToanResponseBody() {
        }
        
        public DanhSachThueChuaThanhToanResponseBody(QuanLiThueXe.ServiceReference1.HOPDONGTHUE[] DanhSachThueChuaThanhToanResult) {
            this.DanhSachThueChuaThanhToanResult = DanhSachThueChuaThanhToanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DanhSachXeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DanhSachXe", Namespace="http://tempuri.org/", Order=0)]
        public QuanLiThueXe.ServiceReference1.DanhSachXeRequestBody Body;
        
        public DanhSachXeRequest() {
        }
        
        public DanhSachXeRequest(QuanLiThueXe.ServiceReference1.DanhSachXeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DanhSachXeRequestBody {
        
        public DanhSachXeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DanhSachXeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DanhSachXeResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuanLiThueXe.ServiceReference1.DanhSachXeResponseBody Body;
        
        public DanhSachXeResponse() {
        }
        
        public DanhSachXeResponse(QuanLiThueXe.ServiceReference1.DanhSachXeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DanhSachXeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuanLiThueXe.ServiceReference1.CHITIETXE1[] DanhSachXeResult;
        
        public DanhSachXeResponseBody() {
        }
        
        public DanhSachXeResponseBody(QuanLiThueXe.ServiceReference1.CHITIETXE1[] DanhSachXeResult) {
            this.DanhSachXeResult = DanhSachXeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ThanhToanTienRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ThanhToanTien", Namespace="http://tempuri.org/", Order=0)]
        public QuanLiThueXe.ServiceReference1.ThanhToanTienRequestBody Body;
        
        public ThanhToanTienRequest() {
        }
        
        public ThanhToanTienRequest(QuanLiThueXe.ServiceReference1.ThanhToanTienRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ThanhToanTienRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sddt;
        
        public ThanhToanTienRequestBody() {
        }
        
        public ThanhToanTienRequestBody(int sddt) {
            this.sddt = sddt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ThanhToanTienResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ThanhToanTienResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuanLiThueXe.ServiceReference1.ThanhToanTienResponseBody Body;
        
        public ThanhToanTienResponse() {
        }
        
        public ThanhToanTienResponse(QuanLiThueXe.ServiceReference1.ThanhToanTienResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ThanhToanTienResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public QuanLiThueXe.ServiceReference1.THANHTOAN[] ThanhToanTienResult;
        
        public ThanhToanTienResponseBody() {
        }
        
        public ThanhToanTienResponseBody(QuanLiThueXe.ServiceReference1.THANHTOAN[] ThanhToanTienResult) {
            this.ThanhToanTienResult = ThanhToanTienResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QLTXMSoapChannel : QuanLiThueXe.ServiceReference1.QLTXMSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QLTXMSoapClient : System.ServiceModel.ClientBase<QuanLiThueXe.ServiceReference1.QLTXMSoap>, QuanLiThueXe.ServiceReference1.QLTXMSoap {
        
        public QLTXMSoapClient() {
        }
        
        public QLTXMSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QLTXMSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLTXMSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLTXMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuanLiThueXe.ServiceReference1.DanhSachThueResponse QuanLiThueXe.ServiceReference1.QLTXMSoap.DanhSachThue(QuanLiThueXe.ServiceReference1.DanhSachThueRequest request) {
            return base.Channel.DanhSachThue(request);
        }
        
        public QuanLiThueXe.ServiceReference1.HOPDONGTHUE[] DanhSachThue() {
            QuanLiThueXe.ServiceReference1.DanhSachThueRequest inValue = new QuanLiThueXe.ServiceReference1.DanhSachThueRequest();
            inValue.Body = new QuanLiThueXe.ServiceReference1.DanhSachThueRequestBody();
            QuanLiThueXe.ServiceReference1.DanhSachThueResponse retVal = ((QuanLiThueXe.ServiceReference1.QLTXMSoap)(this)).DanhSachThue(inValue);
            return retVal.Body.DanhSachThueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuanLiThueXe.ServiceReference1.DanhSachThueResponse> QuanLiThueXe.ServiceReference1.QLTXMSoap.DanhSachThueAsync(QuanLiThueXe.ServiceReference1.DanhSachThueRequest request) {
            return base.Channel.DanhSachThueAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuanLiThueXe.ServiceReference1.DanhSachThueResponse> DanhSachThueAsync() {
            QuanLiThueXe.ServiceReference1.DanhSachThueRequest inValue = new QuanLiThueXe.ServiceReference1.DanhSachThueRequest();
            inValue.Body = new QuanLiThueXe.ServiceReference1.DanhSachThueRequestBody();
            return ((QuanLiThueXe.ServiceReference1.QLTXMSoap)(this)).DanhSachThueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanResponse QuanLiThueXe.ServiceReference1.QLTXMSoap.DanhSachThueChuaThanhToan(QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanRequest request) {
            return base.Channel.DanhSachThueChuaThanhToan(request);
        }
        
        public QuanLiThueXe.ServiceReference1.HOPDONGTHUE[] DanhSachThueChuaThanhToan() {
            QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanRequest inValue = new QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanRequest();
            inValue.Body = new QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanRequestBody();
            QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanResponse retVal = ((QuanLiThueXe.ServiceReference1.QLTXMSoap)(this)).DanhSachThueChuaThanhToan(inValue);
            return retVal.Body.DanhSachThueChuaThanhToanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanResponse> QuanLiThueXe.ServiceReference1.QLTXMSoap.DanhSachThueChuaThanhToanAsync(QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanRequest request) {
            return base.Channel.DanhSachThueChuaThanhToanAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanResponse> DanhSachThueChuaThanhToanAsync() {
            QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanRequest inValue = new QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanRequest();
            inValue.Body = new QuanLiThueXe.ServiceReference1.DanhSachThueChuaThanhToanRequestBody();
            return ((QuanLiThueXe.ServiceReference1.QLTXMSoap)(this)).DanhSachThueChuaThanhToanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuanLiThueXe.ServiceReference1.DanhSachXeResponse QuanLiThueXe.ServiceReference1.QLTXMSoap.DanhSachXe(QuanLiThueXe.ServiceReference1.DanhSachXeRequest request) {
            return base.Channel.DanhSachXe(request);
        }
        
        public QuanLiThueXe.ServiceReference1.CHITIETXE1[] DanhSachXe() {
            QuanLiThueXe.ServiceReference1.DanhSachXeRequest inValue = new QuanLiThueXe.ServiceReference1.DanhSachXeRequest();
            inValue.Body = new QuanLiThueXe.ServiceReference1.DanhSachXeRequestBody();
            QuanLiThueXe.ServiceReference1.DanhSachXeResponse retVal = ((QuanLiThueXe.ServiceReference1.QLTXMSoap)(this)).DanhSachXe(inValue);
            return retVal.Body.DanhSachXeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuanLiThueXe.ServiceReference1.DanhSachXeResponse> QuanLiThueXe.ServiceReference1.QLTXMSoap.DanhSachXeAsync(QuanLiThueXe.ServiceReference1.DanhSachXeRequest request) {
            return base.Channel.DanhSachXeAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuanLiThueXe.ServiceReference1.DanhSachXeResponse> DanhSachXeAsync() {
            QuanLiThueXe.ServiceReference1.DanhSachXeRequest inValue = new QuanLiThueXe.ServiceReference1.DanhSachXeRequest();
            inValue.Body = new QuanLiThueXe.ServiceReference1.DanhSachXeRequestBody();
            return ((QuanLiThueXe.ServiceReference1.QLTXMSoap)(this)).DanhSachXeAsync(inValue);
        }
        
        public void ThemHopDongThue(int maxe, int makh, int manv, System.DateTime ngaythue, System.DateTime ngaytra) {
            base.Channel.ThemHopDongThue(maxe, makh, manv, ngaythue, ngaytra);
        }
        
        public System.Threading.Tasks.Task ThemHopDongThueAsync(int maxe, int makh, int manv, System.DateTime ngaythue, System.DateTime ngaytra) {
            return base.Channel.ThemHopDongThueAsync(maxe, makh, manv, ngaythue, ngaytra);
        }
        
        public void CapNhatHopDong(int sddt) {
            base.Channel.CapNhatHopDong(sddt);
        }
        
        public System.Threading.Tasks.Task CapNhatHopDongAsync(int sddt) {
            return base.Channel.CapNhatHopDongAsync(sddt);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuanLiThueXe.ServiceReference1.ThanhToanTienResponse QuanLiThueXe.ServiceReference1.QLTXMSoap.ThanhToanTien(QuanLiThueXe.ServiceReference1.ThanhToanTienRequest request) {
            return base.Channel.ThanhToanTien(request);
        }
        
        public QuanLiThueXe.ServiceReference1.THANHTOAN[] ThanhToanTien(int sddt) {
            QuanLiThueXe.ServiceReference1.ThanhToanTienRequest inValue = new QuanLiThueXe.ServiceReference1.ThanhToanTienRequest();
            inValue.Body = new QuanLiThueXe.ServiceReference1.ThanhToanTienRequestBody();
            inValue.Body.sddt = sddt;
            QuanLiThueXe.ServiceReference1.ThanhToanTienResponse retVal = ((QuanLiThueXe.ServiceReference1.QLTXMSoap)(this)).ThanhToanTien(inValue);
            return retVal.Body.ThanhToanTienResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuanLiThueXe.ServiceReference1.ThanhToanTienResponse> QuanLiThueXe.ServiceReference1.QLTXMSoap.ThanhToanTienAsync(QuanLiThueXe.ServiceReference1.ThanhToanTienRequest request) {
            return base.Channel.ThanhToanTienAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuanLiThueXe.ServiceReference1.ThanhToanTienResponse> ThanhToanTienAsync(int sddt) {
            QuanLiThueXe.ServiceReference1.ThanhToanTienRequest inValue = new QuanLiThueXe.ServiceReference1.ThanhToanTienRequest();
            inValue.Body = new QuanLiThueXe.ServiceReference1.ThanhToanTienRequestBody();
            inValue.Body.sddt = sddt;
            return ((QuanLiThueXe.ServiceReference1.QLTXMSoap)(this)).ThanhToanTienAsync(inValue);
        }
    }
}
